In [1]:
import pandas as pd
import trackml
from trackml.dataset import load_event

In [2]:
class Preprocessor:
    """
    Preprocessor class will parse dataset under required specifications.
    """
    def __init__(self, cells_data, hits_data, particles_data, truth_data):
        self.cells = pd.read_csv(cells_data)
        self.hits  = pd.read_csv(hits_data)
        self.particles = pd.read_csv(particles_data)
        self.truth = pd.read_csv(truth_data)

In [10]:
hits, cells, particles, truth = load_event('/Users/Eden/Desktop/Datasets/train_100_events/event000001000')

In [28]:
hits

hit_id           x          y       z  volume_id  layer_id  module_id
0            1  -64.409897  -7.163700 -1502.5          7         2          1
1            2  -55.336102   0.635342 -1502.5          7         2          1
2            3  -83.830498  -1.143010 -1502.5          7         2          1
3            4  -96.109100  -8.241030 -1502.5          7         2          1
4            5  -62.673599  -9.371200 -1502.5          7         2          1
...        ...         ...        ...     ...        ...       ...        ...
120934  120935 -763.862976  51.569401  2944.5         18        12         97
120935  120936 -808.705017   3.459260  2944.5         18        12         97
120936  120937 -982.935974  41.460899  2952.5         18        12         98
120937  120938 -942.698975  18.489100  2952.5         18        12         98
120938  120939 -922.890015   2.092850  2952.5         18        12         98

[120939 rows x 7 columns]

In [27]:
from numpy import load

data = load('/Users/Eden/Desktop/event000001000_g000.npz')
lst = data.files
for item in lst:
    print(item)
    print(len(data[item]))
    print(data[item])

X
6437
[[0.03144621 0.8504313  0.0595952 ]
 [0.07216    0.84666234 0.136875  ]
 [0.11557334 0.8430469  0.21927   ]
 ...
 [0.65818244 0.7734815  0.0616    ]
 [0.81695163 0.787495   0.076     ]
 [1.0168136  0.80558014 0.0976    ]]
y
10670
[1. 0. 0. ... 1. 1. 1.]
Ri_rows
10670
[   1    1    1 ... 6434 6435 6436]
Ri_cols
10670
[    0   789  1535 ...  9747 10252 10669]
Ro_rows
10670
[   0    0    0 ... 6433 6434 6435]
Ro_cols
10670
[    0     1     2 ...  9747 10252 10669]
